[package]
name = "jayjay-uniffi"
version = "0.1.0"
description = "UniFFI bindings for JayJay core"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
jayjay-core = { version = "0.1.0", path = "../jayjay-core" }
uniffi = { workspace = true, features = ["cli"] }
thiserror = { workspace = true }
