use gpui::WindowAppearance;
use jayjay_core::DiffThemeColors;

use super::Theme;
use crate::app::config::AppearanceMode;

impl Theme {
    fn dark() -> Self {
        let diff = DiffThemeColors::dark();

        Self {
            is_dark: true,
            sidebar_bg: 0x10131a,
            detail_bg: 0x10131a,
            header_bg: 0x1a1f27,
            row_alt_bg: 0x171b22,
            selected_bg: 0x1f2a3d,
            fg: 0xe6e6e6,
            fg_dim: 0x8a8f99,
            fg_faint: 0x595e68,
            border: 0x252a33,
            row_border: 0x1f242c,
            selected_accent: 0x3b82f6,
            success_fg: 0x77e887,
            wc_accent: 0xf59e0b,
            compare_bg: 0x251a12,
            compare_accent: 0xfb923c,
            dag_line: 0x282d35,
            dag_edge: 0x343942,
            dag_node: 0x4d5159,
            tag_bg: 0x252a33,
            tag_fg: 0xc6cad1,
            tag_wc_bg: 0x2a3550,
            tag_wc_fg: 0x93c5fd,
            tag_conflict_bg: 0x4a1f1f,
            tag_conflict_fg: 0xfca5a5,
            tag_divergent_bg: 0x4a2f03,
            tag_divergent_fg: 0xff9f0a,
            tag_bookmark_bg: 0x2a2f38,
            tag_bookmark_fg: 0xb9bfca,
            tag_bookmark_icon: 0x86efac,
            change_id_prefix: jayjay_core::change_id_prefix_color(true),
            tag_tag_bg: 0x2a2f38,
            tag_tag_fg: 0xb9bfca,
            tag_tag_icon: 0x93c5fd,
            diff_added_bg: diff.added_bg,
            diff_removed_bg: diff.removed_bg,
            diff_context_bg: diff.context_bg,
            diff_separator_bg: diff.separator_bg,
            diff_conflict_header_bg: diff.conflict_header_bg,
            diff_conflict_section_bg: diff.conflict_section_bg,
            diff_conflict_content_bg: diff.conflict_content_bg,
            diff_conflict_header_fg: diff.conflict_header_fg,
            diff_conflict_section_fg: diff.conflict_section_fg,
            diff_conflict_stripe: diff.conflict_stripe,
            diff_added_word_bg: diff.added_word_bg,
            diff_removed_word_bg: diff.removed_word_bg,
            diff_gutter_bg: diff.gutter_bg,
            diff_gutter_fg: diff.gutter_fg,
            diff_gutter_added_fg: diff.gutter_added_fg,
            diff_gutter_removed_fg: diff.gutter_removed_fg,
            diff_text_context: diff.text_context,
            diff_text_added: diff.text_added,
            diff_text_removed: diff.text_removed,
            diff_text_dim: diff.text_dim,
            tok_keyword: diff.tok_keyword,
            tok_string: diff.tok_string,
            tok_comment: diff.tok_comment,
            tok_number: diff.tok_number,
            tok_type: diff.tok_type,
            tag_added_bg: 0x14532d,
            tag_added_fg: 0x86efac,
            tag_removed_bg: 0x7f1d1d,
            tag_removed_fg: 0xfecaca,
            tag_modified_bg: 0x1e3a8a,
            tag_modified_fg: 0xbfdbfe,
            tag_renamed_bg: 0x78350f,
            tag_renamed_fg: 0xfde68a,
            file_added_color: 0x30d158,
            file_removed_color: 0xff453a,
            file_modified_color: 0xff9f0a,
            file_renamed_color: 0x0a84ff,
            file_lfs_color: 0xbf5af2,
            error_fg: 0xff6b6b,
            find_match_bg: diff.find_match_bg,
            find_match_fg: diff.find_match_fg,
            toggle_active_bg: 0x2a3550,
            toggle_active_fg: 0xbfdbfe,
            toggle_inactive_bg: 0x252a33,
            toggle_inactive_fg: 0xc6cad1,
            toolbar_bg: 0x1a1f27,
            toolbar_group_bg: 0x1d2129,
        }
    }

    pub fn light() -> Self {
        let diff = DiffThemeColors::light();

        Self {
            is_dark: false,
            sidebar_bg: 0xffffff,
            detail_bg: 0xffffff,
            header_bg: 0xffffff,
            row_alt_bg: 0xf0f2f5,
            selected_bg: 0xd9e6fa,
            fg: 0x1f2328,
            fg_dim: 0x57606a,
            fg_faint: 0x848b94,
            border: 0xd0d7de,
            row_border: 0xe2e6eb,
            selected_accent: 0x3b82f6,
            success_fg: 0x14532d,
            wc_accent: 0xea580c,
            compare_bg: 0xfff7ed,
            compare_accent: 0xf97316,
            dag_line: 0xd9d9d9,
            dag_edge: 0xcacaca,
            dag_node: 0xb8b8b8,
            tag_bg: 0xe6e9ee,
            tag_fg: 0x47525e,
            tag_wc_bg: 0xddeaff,
            tag_wc_fg: 0x1d4ed8,
            tag_conflict_bg: 0xfde0e0,
            tag_conflict_fg: 0x991b1b,
            tag_divergent_bg: 0xffead0,
            tag_divergent_fg: 0xff9500,
            tag_bookmark_bg: 0xe6e9ee,
            tag_bookmark_fg: 0x4a5360,
            tag_bookmark_icon: 0x16a34a,
            change_id_prefix: jayjay_core::change_id_prefix_color(false),
            tag_tag_bg: 0xe6e9ee,
            tag_tag_fg: 0x4a5360,
            tag_tag_icon: 0x1d4ed8,
            diff_added_bg: diff.added_bg,
            diff_removed_bg: diff.removed_bg,
            diff_context_bg: diff.context_bg,
            diff_separator_bg: diff.separator_bg,
            diff_conflict_header_bg: diff.conflict_header_bg,
            diff_conflict_section_bg: diff.conflict_section_bg,
            diff_conflict_content_bg: diff.conflict_content_bg,
            diff_conflict_header_fg: diff.conflict_header_fg,
            diff_conflict_section_fg: diff.conflict_section_fg,
            diff_conflict_stripe: diff.conflict_stripe,
            diff_added_word_bg: diff.added_word_bg,
            diff_removed_word_bg: diff.removed_word_bg,
            diff_gutter_bg: diff.gutter_bg,
            diff_gutter_fg: diff.gutter_fg,
            diff_gutter_added_fg: diff.gutter_added_fg,
            diff_gutter_removed_fg: diff.gutter_removed_fg,
            diff_text_context: diff.text_context,
            diff_text_added: diff.text_added,
            diff_text_removed: diff.text_removed,
            diff_text_dim: diff.text_dim,
            tok_keyword: diff.tok_keyword,
            tok_string: diff.tok_string,
            tok_comment: diff.tok_comment,
            tok_number: diff.tok_number,
            tok_type: diff.tok_type,
            tag_added_bg: 0xddf5e2,
            tag_added_fg: 0x14532d,
            tag_removed_bg: 0xfceeee,
            tag_removed_fg: 0x991b1b,
            tag_modified_bg: 0xddeaff,
            tag_modified_fg: 0x1d4ed8,
            tag_renamed_bg: 0xfde7c4,
            tag_renamed_fg: 0x854d0e,
            file_added_color: 0x34c759,
            file_removed_color: 0xff3b30,
            file_modified_color: 0xff9500,
            file_renamed_color: 0x007aff,
            file_lfs_color: 0xaf52de,
            error_fg: 0xb00020,
            find_match_bg: diff.find_match_bg,
            find_match_fg: diff.find_match_fg,
            toggle_active_bg: 0xddeaff,
            toggle_active_fg: 0x1d4ed8,
            toggle_inactive_bg: 0xe6e9ee,
            toggle_inactive_fg: 0x47525e,
            toolbar_bg: 0xf8f8f8,
            toolbar_group_bg: 0xffffff,
        }
    }

    pub fn for_appearance(mode: AppearanceMode, system: WindowAppearance) -> Self {
        match mode {
            AppearanceMode::Light => Self::light(),
            AppearanceMode::Dark => Self::dark(),
            AppearanceMode::System => match system {
                WindowAppearance::Light | WindowAppearance::VibrantLight => Self::light(),
                WindowAppearance::Dark | WindowAppearance::VibrantDark => Self::dark(),
            },
        }
    }
}
