// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(jayjay_uniffiFFI)
import jayjay_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_jayjay_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_jayjay_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureJayjayUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol JayJayRepoProtocol: AnyObject, Sendable {
    
    func abandon(rev: String) throws 
    
    func createBookmark(name: String, rev: String) throws 
    
    func deleteBookmark(name: String) throws 
    
    func describe(rev: String, message: String) throws 
    
    func gitFetch(remote: String) throws 
    
    func gitPush(bookmark: String) throws 
    
    func listBookmarks() throws  -> [BookmarkInfo]
    
    func log(revset: String) throws  -> [ChangeInfo]
    
    func moveBookmark(name: String, toRev: String) throws 
    
    func newChange(parent: String, message: String) throws 
    
    func path()  -> String
    
    func rebase(rev: String, dest: String) throws 
    
    func show(rev: String) throws  -> ChangeDetail
    
    func squash(rev: String, intoRev: String?) throws 
    
}
open class JayJayRepo: JayJayRepoProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_jayjay_uniffi_fn_clone_jayjayrepo(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_jayjay_uniffi_fn_free_jayjayrepo(handle, $0) }
    }

    
public static func `open`(path: String)throws  -> JayJayRepo  {
    return try  FfiConverterTypeJayJayRepo_lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_constructor_jayjayrepo_open(
        FfiConverterString.lower(path),$0
    )
})
}
    

    
open func abandon(rev: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_abandon(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),$0
    )
}
}
    
open func createBookmark(name: String, rev: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_create_bookmark(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(rev),$0
    )
}
}
    
open func deleteBookmark(name: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_delete_bookmark(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
}
}
    
open func describe(rev: String, message: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_describe(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func gitFetch(remote: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_git_fetch(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(remote),$0
    )
}
}
    
open func gitPush(bookmark: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_git_push(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(bookmark),$0
    )
}
}
    
open func listBookmarks()throws  -> [BookmarkInfo]  {
    return try  FfiConverterSequenceTypeBookmarkInfo.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_list_bookmarks(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func log(revset: String)throws  -> [ChangeInfo]  {
    return try  FfiConverterSequenceTypeChangeInfo.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_log(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(revset),$0
    )
})
}
    
open func moveBookmark(name: String, toRev: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_move_bookmark(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(toRev),$0
    )
}
}
    
open func newChange(parent: String, message: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_new_change(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(parent),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func path() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func rebase(rev: String, dest: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_rebase(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterString.lower(dest),$0
    )
}
}
    
open func show(rev: String)throws  -> ChangeDetail  {
    return try  FfiConverterTypeChangeDetail_lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_show(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),$0
    )
})
}
    
open func squash(rev: String, intoRev: String?)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_squash(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterOptionString.lower(intoRev),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJayJayRepo: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = JayJayRepo

    public static func lift(_ handle: UInt64) throws -> JayJayRepo {
        return JayJayRepo(unsafeFromHandle: handle)
    }

    public static func lower(_ value: JayJayRepo) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JayJayRepo {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: JayJayRepo, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayRepo_lift(_ handle: UInt64) throws -> JayJayRepo {
    return try FfiConverterTypeJayJayRepo.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayRepo_lower(_ value: JayJayRepo) -> UInt64 {
    return FfiConverterTypeJayJayRepo.lower(value)
}




public struct BookmarkInfo: Equatable, Hashable {
    public var name: String
    public var changeId: String
    public var isTrackingRemote: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, changeId: String, isTrackingRemote: Bool) {
        self.name = name
        self.changeId = changeId
        self.isTrackingRemote = isTrackingRemote
    }

    

    
}

#if compiler(>=6)
extension BookmarkInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBookmarkInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BookmarkInfo {
        return
            try BookmarkInfo(
                name: FfiConverterString.read(from: &buf), 
                changeId: FfiConverterString.read(from: &buf), 
                isTrackingRemote: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: BookmarkInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.changeId, into: &buf)
        FfiConverterBool.write(value.isTrackingRemote, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBookmarkInfo_lift(_ buf: RustBuffer) throws -> BookmarkInfo {
    return try FfiConverterTypeBookmarkInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBookmarkInfo_lower(_ value: BookmarkInfo) -> RustBuffer {
    return FfiConverterTypeBookmarkInfo.lower(value)
}


public struct ChangeDetail: Equatable, Hashable {
    public var info: ChangeInfo
    public var diff: [DiffHunk]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(info: ChangeInfo, diff: [DiffHunk]) {
        self.info = info
        self.diff = diff
    }

    

    
}

#if compiler(>=6)
extension ChangeDetail: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChangeDetail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChangeDetail {
        return
            try ChangeDetail(
                info: FfiConverterTypeChangeInfo.read(from: &buf), 
                diff: FfiConverterSequenceTypeDiffHunk.read(from: &buf)
        )
    }

    public static func write(_ value: ChangeDetail, into buf: inout [UInt8]) {
        FfiConverterTypeChangeInfo.write(value.info, into: &buf)
        FfiConverterSequenceTypeDiffHunk.write(value.diff, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeDetail_lift(_ buf: RustBuffer) throws -> ChangeDetail {
    return try FfiConverterTypeChangeDetail.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeDetail_lower(_ value: ChangeDetail) -> RustBuffer {
    return FfiConverterTypeChangeDetail.lower(value)
}


public struct ChangeInfo: Equatable, Hashable {
    public var changeId: String
    public var commitId: String
    public var description: String
    public var author: String
    public var email: String
    public var timestampMillis: Int64
    public var parents: [String]
    public var bookmarks: [String]
    public var isWorkingCopy: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(changeId: String, commitId: String, description: String, author: String, email: String, timestampMillis: Int64, parents: [String], bookmarks: [String], isWorkingCopy: Bool) {
        self.changeId = changeId
        self.commitId = commitId
        self.description = description
        self.author = author
        self.email = email
        self.timestampMillis = timestampMillis
        self.parents = parents
        self.bookmarks = bookmarks
        self.isWorkingCopy = isWorkingCopy
    }

    

    
}

#if compiler(>=6)
extension ChangeInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChangeInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChangeInfo {
        return
            try ChangeInfo(
                changeId: FfiConverterString.read(from: &buf), 
                commitId: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                author: FfiConverterString.read(from: &buf), 
                email: FfiConverterString.read(from: &buf), 
                timestampMillis: FfiConverterInt64.read(from: &buf), 
                parents: FfiConverterSequenceString.read(from: &buf), 
                bookmarks: FfiConverterSequenceString.read(from: &buf), 
                isWorkingCopy: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ChangeInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.changeId, into: &buf)
        FfiConverterString.write(value.commitId, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.author, into: &buf)
        FfiConverterString.write(value.email, into: &buf)
        FfiConverterInt64.write(value.timestampMillis, into: &buf)
        FfiConverterSequenceString.write(value.parents, into: &buf)
        FfiConverterSequenceString.write(value.bookmarks, into: &buf)
        FfiConverterBool.write(value.isWorkingCopy, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeInfo_lift(_ buf: RustBuffer) throws -> ChangeInfo {
    return try FfiConverterTypeChangeInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeInfo_lower(_ value: ChangeInfo) -> RustBuffer {
    return FfiConverterTypeChangeInfo.lower(value)
}


public struct DiffHunk: Equatable, Hashable {
    public var path: String
    public var oldContent: String?
    public var newContent: String?
    public var hunkType: HunkType

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, oldContent: String?, newContent: String?, hunkType: HunkType) {
        self.path = path
        self.oldContent = oldContent
        self.newContent = newContent
        self.hunkType = hunkType
    }

    

    
}

#if compiler(>=6)
extension DiffHunk: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiffHunk: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiffHunk {
        return
            try DiffHunk(
                path: FfiConverterString.read(from: &buf), 
                oldContent: FfiConverterOptionString.read(from: &buf), 
                newContent: FfiConverterOptionString.read(from: &buf), 
                hunkType: FfiConverterTypeHunkType.read(from: &buf)
        )
    }

    public static func write(_ value: DiffHunk, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterOptionString.write(value.oldContent, into: &buf)
        FfiConverterOptionString.write(value.newContent, into: &buf)
        FfiConverterTypeHunkType.write(value.hunkType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffHunk_lift(_ buf: RustBuffer) throws -> DiffHunk {
    return try FfiConverterTypeDiffHunk.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffHunk_lower(_ value: DiffHunk) -> RustBuffer {
    return FfiConverterTypeDiffHunk.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum HunkType: Equatable, Hashable {
    
    case added
    case removed
    case modified





}

#if compiler(>=6)
extension HunkType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHunkType: FfiConverterRustBuffer {
    typealias SwiftType = HunkType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HunkType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .added
        
        case 2: return .removed
        
        case 3: return .modified
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HunkType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .added:
            writeInt(&buf, Int32(1))
        
        
        case .removed:
            writeInt(&buf, Int32(2))
        
        
        case .modified:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHunkType_lift(_ buf: RustBuffer) throws -> HunkType {
    return try FfiConverterTypeHunkType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHunkType_lower(_ value: HunkType) -> RustBuffer {
    return FfiConverterTypeHunkType.lower(value)
}



public enum JayJayError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case RepoNotFound(path: String
    )
    case RevNotFound(rev: String
    )
    case Internal(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension JayJayError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJayJayError: FfiConverterRustBuffer {
    typealias SwiftType = JayJayError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JayJayError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .RepoNotFound(
            path: try FfiConverterString.read(from: &buf)
            )
        case 2: return .RevNotFound(
            rev: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: JayJayError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .RepoNotFound(path):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(path, into: &buf)
            
        
        case let .RevNotFound(rev):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(rev, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayError_lift(_ buf: RustBuffer) throws -> JayJayError {
    return try FfiConverterTypeJayJayError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayError_lower(_ value: JayJayError) -> RustBuffer {
    return FfiConverterTypeJayJayError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBookmarkInfo: FfiConverterRustBuffer {
    typealias SwiftType = [BookmarkInfo]

    public static func write(_ value: [BookmarkInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBookmarkInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BookmarkInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [BookmarkInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBookmarkInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChangeInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ChangeInfo]

    public static func write(_ value: [ChangeInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChangeInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChangeInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChangeInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChangeInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDiffHunk: FfiConverterRustBuffer {
    typealias SwiftType = [DiffHunk]

    public static func write(_ value: [DiffHunk], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDiffHunk.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DiffHunk] {
        let len: Int32 = try readInt(&buf)
        var seq = [DiffHunk]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDiffHunk.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_jayjay_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_abandon() != 13204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_create_bookmark() != 35749) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_delete_bookmark() != 1256) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_describe() != 32905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_git_fetch() != 62698) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_git_push() != 21077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_list_bookmarks() != 63540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_log() != 41168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_move_bookmark() != 46851) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_new_change() != 15291) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_path() != 44247) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_rebase() != 18128) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_show() != 24425) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_squash() != 1788) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_constructor_jayjayrepo_open() != 60052) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureJayjayUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all