mod about;
mod appearance;
mod cli;
pub mod cli_diagnostics;
mod cli_row;
pub mod config;
mod data_privacy;
mod diff;
mod dropdown;
mod feedback;
mod integrations;
mod loaders;
mod section;
pub(crate) mod shared;
mod sidebar;
pub mod tools;
mod view;
mod workflow;

pub use section::SettingsSection;
pub use view::SettingsView;
