// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(JayJayFFI)
import JayJayFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_jayjay_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_jayjay_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureJayjayUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol JayJayRepoProtocol: AnyObject, Sendable {
    
    func abandon(rev: String) throws 
    
    func commitWithSubmodules(message: String) throws 
    
    func computeNativeDiff(path: String, oldContent: String, newContent: String)  -> FileDiff
    
    func createBookmark(name: String, rev: String) throws 
    
    func deleteBookmark(name: String) throws 
    
    func deleteFiles(paths: [String]) throws 
    
    func describe(rev: String, message: String) throws 
    
    func diffSummary() throws  -> String
    
    func dirtySubmodules() throws  -> [String]
    
    func generateCommitMessage(diffSummary: String)  -> String?
    
    func gitFetch(remote: String) throws  -> String
    
    func gitPush(bookmark: String) throws  -> String
    
    func ignoreAndUntrack(paths: [String]) throws 
    
    func jjCommit(message: String) throws 
    
    func jjConfig() throws  -> String
    
    func jjConfigPath() throws  -> String
    
    func listBookmarks() throws  -> [BookmarkInfo]
    
    func log(revset: String) throws  -> [ChangeInfo]
    
    func logGraph(revset: String) throws  -> [GraphEntry]
    
    func moveBookmark(name: String, toRev: String) throws 
    
    func newChange(parent: String, message: String) throws 
    
    func opLog() throws  -> [OpLogEntry]
    
    func opRestore(opId: String) throws 
    
    func path()  -> String
    
    func rebase(rev: String, dest: String) throws 
    
    func refreshWorkingCopy() throws 
    
    func restoreFiles(rev: String, paths: [String]) throws 
    
    func show(rev: String) throws  -> ChangeDetail
    
    /**
     * Single file with content.
     */
    func showFile(rev: String, path: String) throws  -> DiffHunk
    
    /**
     * Fast: file list without content.
     */
    func showSummary(rev: String) throws  -> ChangeDetail
    
    func split(rev: String, paths: [String], message: String) throws 
    
    func squash(rev: String, intoRev: String?) throws 
    
}
open class JayJayRepo: JayJayRepoProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_jayjay_uniffi_fn_clone_jayjayrepo(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_jayjay_uniffi_fn_free_jayjayrepo(handle, $0) }
    }

    
public static func `open`(path: String)throws  -> JayJayRepo  {
    return try  FfiConverterTypeJayJayRepo_lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_constructor_jayjayrepo_open(
        FfiConverterString.lower(path),$0
    )
})
}
    

    
open func abandon(rev: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_abandon(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),$0
    )
}
}
    
open func commitWithSubmodules(message: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_commit_with_submodules(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func computeNativeDiff(path: String, oldContent: String, newContent: String) -> FileDiff  {
    return try!  FfiConverterTypeFileDiff_lift(try! rustCall() {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_compute_native_diff(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),
        FfiConverterString.lower(oldContent),
        FfiConverterString.lower(newContent),$0
    )
})
}
    
open func createBookmark(name: String, rev: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_create_bookmark(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(rev),$0
    )
}
}
    
open func deleteBookmark(name: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_delete_bookmark(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
}
}
    
open func deleteFiles(paths: [String])throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_delete_files(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(paths),$0
    )
}
}
    
open func describe(rev: String, message: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_describe(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func diffSummary()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_diff_summary(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func dirtySubmodules()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_dirty_submodules(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func generateCommitMessage(diffSummary: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_generate_commit_message(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(diffSummary),$0
    )
})
}
    
open func gitFetch(remote: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_git_fetch(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(remote),$0
    )
})
}
    
open func gitPush(bookmark: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_git_push(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(bookmark),$0
    )
})
}
    
open func ignoreAndUntrack(paths: [String])throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_ignore_and_untrack(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(paths),$0
    )
}
}
    
open func jjCommit(message: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_jj_commit(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func jjConfig()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_jj_config(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func jjConfigPath()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_jj_config_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func listBookmarks()throws  -> [BookmarkInfo]  {
    return try  FfiConverterSequenceTypeBookmarkInfo.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_list_bookmarks(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func log(revset: String)throws  -> [ChangeInfo]  {
    return try  FfiConverterSequenceTypeChangeInfo.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_log(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(revset),$0
    )
})
}
    
open func logGraph(revset: String)throws  -> [GraphEntry]  {
    return try  FfiConverterSequenceTypeGraphEntry.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_log_graph(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(revset),$0
    )
})
}
    
open func moveBookmark(name: String, toRev: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_move_bookmark(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(toRev),$0
    )
}
}
    
open func newChange(parent: String, message: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_new_change(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(parent),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func opLog()throws  -> [OpLogEntry]  {
    return try  FfiConverterSequenceTypeOpLogEntry.lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_op_log(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func opRestore(opId: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_op_restore(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(opId),$0
    )
}
}
    
open func path() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func rebase(rev: String, dest: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_rebase(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterString.lower(dest),$0
    )
}
}
    
open func refreshWorkingCopy()throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_refresh_working_copy(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func restoreFiles(rev: String, paths: [String])throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_restore_files(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterSequenceString.lower(paths),$0
    )
}
}
    
open func show(rev: String)throws  -> ChangeDetail  {
    return try  FfiConverterTypeChangeDetail_lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_show(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),$0
    )
})
}
    
    /**
     * Single file with content.
     */
open func showFile(rev: String, path: String)throws  -> DiffHunk  {
    return try  FfiConverterTypeDiffHunk_lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_show_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Fast: file list without content.
     */
open func showSummary(rev: String)throws  -> ChangeDetail  {
    return try  FfiConverterTypeChangeDetail_lift(try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_show_summary(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),$0
    )
})
}
    
open func split(rev: String, paths: [String], message: String)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_split(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterSequenceString.lower(paths),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func squash(rev: String, intoRev: String?)throws   {try rustCallWithError(FfiConverterTypeJayJayError_lift) {
    uniffi_jayjay_uniffi_fn_method_jayjayrepo_squash(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(rev),
        FfiConverterOptionString.lower(intoRev),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJayJayRepo: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = JayJayRepo

    public static func lift(_ handle: UInt64) throws -> JayJayRepo {
        return JayJayRepo(unsafeFromHandle: handle)
    }

    public static func lower(_ value: JayJayRepo) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JayJayRepo {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: JayJayRepo, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayRepo_lift(_ handle: UInt64) throws -> JayJayRepo {
    return try FfiConverterTypeJayJayRepo.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayRepo_lower(_ value: JayJayRepo) -> UInt64 {
    return FfiConverterTypeJayJayRepo.lower(value)
}




public struct BookmarkInfo: Equatable, Hashable {
    public let name: String
    public let changeId: String
    public let isTrackingRemote: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, changeId: String, isTrackingRemote: Bool) {
        self.name = name
        self.changeId = changeId
        self.isTrackingRemote = isTrackingRemote
    }

    

    
}

#if compiler(>=6)
extension BookmarkInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBookmarkInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BookmarkInfo {
        return
            try BookmarkInfo(
                name: FfiConverterString.read(from: &buf), 
                changeId: FfiConverterString.read(from: &buf), 
                isTrackingRemote: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: BookmarkInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.changeId, into: &buf)
        FfiConverterBool.write(value.isTrackingRemote, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBookmarkInfo_lift(_ buf: RustBuffer) throws -> BookmarkInfo {
    return try FfiConverterTypeBookmarkInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBookmarkInfo_lower(_ value: BookmarkInfo) -> RustBuffer {
    return FfiConverterTypeBookmarkInfo.lower(value)
}


public struct ChangeDetail: Equatable, Hashable {
    public let info: ChangeInfo
    public let diff: [DiffHunk]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(info: ChangeInfo, diff: [DiffHunk]) {
        self.info = info
        self.diff = diff
    }

    

    
}

#if compiler(>=6)
extension ChangeDetail: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChangeDetail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChangeDetail {
        return
            try ChangeDetail(
                info: FfiConverterTypeChangeInfo.read(from: &buf), 
                diff: FfiConverterSequenceTypeDiffHunk.read(from: &buf)
        )
    }

    public static func write(_ value: ChangeDetail, into buf: inout [UInt8]) {
        FfiConverterTypeChangeInfo.write(value.info, into: &buf)
        FfiConverterSequenceTypeDiffHunk.write(value.diff, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeDetail_lift(_ buf: RustBuffer) throws -> ChangeDetail {
    return try FfiConverterTypeChangeDetail.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeDetail_lower(_ value: ChangeDetail) -> RustBuffer {
    return FfiConverterTypeChangeDetail.lower(value)
}


public struct ChangeInfo: Equatable, Hashable {
    public let changeId: String
    public let commitId: String
    public let description: String
    public let author: String
    public let email: String
    public let timestampMillis: Int64
    public let parents: [String]
    public let bookmarks: [String]
    public let isWorkingCopy: Bool
    public let hasConflict: Bool
    public let isEmpty: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(changeId: String, commitId: String, description: String, author: String, email: String, timestampMillis: Int64, parents: [String], bookmarks: [String], isWorkingCopy: Bool, hasConflict: Bool, isEmpty: Bool) {
        self.changeId = changeId
        self.commitId = commitId
        self.description = description
        self.author = author
        self.email = email
        self.timestampMillis = timestampMillis
        self.parents = parents
        self.bookmarks = bookmarks
        self.isWorkingCopy = isWorkingCopy
        self.hasConflict = hasConflict
        self.isEmpty = isEmpty
    }

    

    
}

#if compiler(>=6)
extension ChangeInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChangeInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChangeInfo {
        return
            try ChangeInfo(
                changeId: FfiConverterString.read(from: &buf), 
                commitId: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                author: FfiConverterString.read(from: &buf), 
                email: FfiConverterString.read(from: &buf), 
                timestampMillis: FfiConverterInt64.read(from: &buf), 
                parents: FfiConverterSequenceString.read(from: &buf), 
                bookmarks: FfiConverterSequenceString.read(from: &buf), 
                isWorkingCopy: FfiConverterBool.read(from: &buf), 
                hasConflict: FfiConverterBool.read(from: &buf), 
                isEmpty: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ChangeInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.changeId, into: &buf)
        FfiConverterString.write(value.commitId, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.author, into: &buf)
        FfiConverterString.write(value.email, into: &buf)
        FfiConverterInt64.write(value.timestampMillis, into: &buf)
        FfiConverterSequenceString.write(value.parents, into: &buf)
        FfiConverterSequenceString.write(value.bookmarks, into: &buf)
        FfiConverterBool.write(value.isWorkingCopy, into: &buf)
        FfiConverterBool.write(value.hasConflict, into: &buf)
        FfiConverterBool.write(value.isEmpty, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeInfo_lift(_ buf: RustBuffer) throws -> ChangeInfo {
    return try FfiConverterTypeChangeInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChangeInfo_lower(_ value: ChangeInfo) -> RustBuffer {
    return FfiConverterTypeChangeInfo.lower(value)
}


public struct DiffHunk: Equatable, Hashable {
    public let path: String
    public let oldPath: String?
    public let oldContent: String?
    public let newContent: String?
    public let hunkType: HunkType

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, oldPath: String?, oldContent: String?, newContent: String?, hunkType: HunkType) {
        self.path = path
        self.oldPath = oldPath
        self.oldContent = oldContent
        self.newContent = newContent
        self.hunkType = hunkType
    }

    

    
}

#if compiler(>=6)
extension DiffHunk: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiffHunk: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiffHunk {
        return
            try DiffHunk(
                path: FfiConverterString.read(from: &buf), 
                oldPath: FfiConverterOptionString.read(from: &buf), 
                oldContent: FfiConverterOptionString.read(from: &buf), 
                newContent: FfiConverterOptionString.read(from: &buf), 
                hunkType: FfiConverterTypeHunkType.read(from: &buf)
        )
    }

    public static func write(_ value: DiffHunk, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterOptionString.write(value.oldPath, into: &buf)
        FfiConverterOptionString.write(value.oldContent, into: &buf)
        FfiConverterOptionString.write(value.newContent, into: &buf)
        FfiConverterTypeHunkType.write(value.hunkType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffHunk_lift(_ buf: RustBuffer) throws -> DiffHunk {
    return try FfiConverterTypeDiffHunk.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffHunk_lower(_ value: DiffHunk) -> RustBuffer {
    return FfiConverterTypeDiffHunk.lower(value)
}


public struct FileDiff: Equatable, Hashable {
    public let path: String
    public let language: String
    public let lines: [NativeDiffLine]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, language: String, lines: [NativeDiffLine]) {
        self.path = path
        self.language = language
        self.lines = lines
    }

    

    
}

#if compiler(>=6)
extension FileDiff: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFileDiff: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FileDiff {
        return
            try FileDiff(
                path: FfiConverterString.read(from: &buf), 
                language: FfiConverterString.read(from: &buf), 
                lines: FfiConverterSequenceTypeNativeDiffLine.read(from: &buf)
        )
    }

    public static func write(_ value: FileDiff, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.language, into: &buf)
        FfiConverterSequenceTypeNativeDiffLine.write(value.lines, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileDiff_lift(_ buf: RustBuffer) throws -> FileDiff {
    return try FfiConverterTypeFileDiff.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileDiff_lower(_ value: FileDiff) -> RustBuffer {
    return FfiConverterTypeFileDiff.lower(value)
}


public struct GraphEdge: Equatable, Hashable {
    public let target: String
    public let edgeType: EdgeType

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(target: String, edgeType: EdgeType) {
        self.target = target
        self.edgeType = edgeType
    }

    

    
}

#if compiler(>=6)
extension GraphEdge: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGraphEdge: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GraphEdge {
        return
            try GraphEdge(
                target: FfiConverterString.read(from: &buf), 
                edgeType: FfiConverterTypeEdgeType.read(from: &buf)
        )
    }

    public static func write(_ value: GraphEdge, into buf: inout [UInt8]) {
        FfiConverterString.write(value.target, into: &buf)
        FfiConverterTypeEdgeType.write(value.edgeType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphEdge_lift(_ buf: RustBuffer) throws -> GraphEdge {
    return try FfiConverterTypeGraphEdge.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphEdge_lower(_ value: GraphEdge) -> RustBuffer {
    return FfiConverterTypeGraphEdge.lower(value)
}


public struct GraphEntry: Equatable, Hashable {
    public let change: ChangeInfo
    public let edges: [GraphEdge]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(change: ChangeInfo, edges: [GraphEdge]) {
        self.change = change
        self.edges = edges
    }

    

    
}

#if compiler(>=6)
extension GraphEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGraphEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GraphEntry {
        return
            try GraphEntry(
                change: FfiConverterTypeChangeInfo.read(from: &buf), 
                edges: FfiConverterSequenceTypeGraphEdge.read(from: &buf)
        )
    }

    public static func write(_ value: GraphEntry, into buf: inout [UInt8]) {
        FfiConverterTypeChangeInfo.write(value.change, into: &buf)
        FfiConverterSequenceTypeGraphEdge.write(value.edges, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphEntry_lift(_ buf: RustBuffer) throws -> GraphEntry {
    return try FfiConverterTypeGraphEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphEntry_lower(_ value: GraphEntry) -> RustBuffer {
    return FfiConverterTypeGraphEntry.lower(value)
}


public struct NativeDiffLine: Equatable, Hashable {
    public let oldLineNo: UInt32?
    public let newLineNo: UInt32?
    public let style: DiffSpanStyle
    public let spans: [NativeDiffSpan]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(oldLineNo: UInt32?, newLineNo: UInt32?, style: DiffSpanStyle, spans: [NativeDiffSpan]) {
        self.oldLineNo = oldLineNo
        self.newLineNo = newLineNo
        self.style = style
        self.spans = spans
    }

    

    
}

#if compiler(>=6)
extension NativeDiffLine: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeDiffLine: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeDiffLine {
        return
            try NativeDiffLine(
                oldLineNo: FfiConverterOptionUInt32.read(from: &buf), 
                newLineNo: FfiConverterOptionUInt32.read(from: &buf), 
                style: FfiConverterTypeDiffSpanStyle.read(from: &buf), 
                spans: FfiConverterSequenceTypeNativeDiffSpan.read(from: &buf)
        )
    }

    public static func write(_ value: NativeDiffLine, into buf: inout [UInt8]) {
        FfiConverterOptionUInt32.write(value.oldLineNo, into: &buf)
        FfiConverterOptionUInt32.write(value.newLineNo, into: &buf)
        FfiConverterTypeDiffSpanStyle.write(value.style, into: &buf)
        FfiConverterSequenceTypeNativeDiffSpan.write(value.spans, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDiffLine_lift(_ buf: RustBuffer) throws -> NativeDiffLine {
    return try FfiConverterTypeNativeDiffLine.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDiffLine_lower(_ value: NativeDiffLine) -> RustBuffer {
    return FfiConverterTypeNativeDiffLine.lower(value)
}


public struct NativeDiffSpan: Equatable, Hashable {
    public let text: String
    public let style: DiffSpanStyle
    public let token: SyntaxToken

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, style: DiffSpanStyle, token: SyntaxToken) {
        self.text = text
        self.style = style
        self.token = token
    }

    

    
}

#if compiler(>=6)
extension NativeDiffSpan: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeDiffSpan: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeDiffSpan {
        return
            try NativeDiffSpan(
                text: FfiConverterString.read(from: &buf), 
                style: FfiConverterTypeDiffSpanStyle.read(from: &buf), 
                token: FfiConverterTypeSyntaxToken.read(from: &buf)
        )
    }

    public static func write(_ value: NativeDiffSpan, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterTypeDiffSpanStyle.write(value.style, into: &buf)
        FfiConverterTypeSyntaxToken.write(value.token, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDiffSpan_lift(_ buf: RustBuffer) throws -> NativeDiffSpan {
    return try FfiConverterTypeNativeDiffSpan.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDiffSpan_lower(_ value: NativeDiffSpan) -> RustBuffer {
    return FfiConverterTypeNativeDiffSpan.lower(value)
}


public struct OpLogEntry: Equatable, Hashable {
    public let id: String
    public let description: String
    public let timestamp: String
    public let isCurrent: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, description: String, timestamp: String, isCurrent: Bool) {
        self.id = id
        self.description = description
        self.timestamp = timestamp
        self.isCurrent = isCurrent
    }

    

    
}

#if compiler(>=6)
extension OpLogEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOpLogEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OpLogEntry {
        return
            try OpLogEntry(
                id: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterString.read(from: &buf), 
                isCurrent: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: OpLogEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.timestamp, into: &buf)
        FfiConverterBool.write(value.isCurrent, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpLogEntry_lift(_ buf: RustBuffer) throws -> OpLogEntry {
    return try FfiConverterTypeOpLogEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpLogEntry_lower(_ value: OpLogEntry) -> RustBuffer {
    return FfiConverterTypeOpLogEntry.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DiffSpanStyle: Equatable, Hashable {
    
    case context
    case added
    case removed
    case unchanged
    case separator





}

#if compiler(>=6)
extension DiffSpanStyle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiffSpanStyle: FfiConverterRustBuffer {
    typealias SwiftType = DiffSpanStyle

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiffSpanStyle {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .context
        
        case 2: return .added
        
        case 3: return .removed
        
        case 4: return .unchanged
        
        case 5: return .separator
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DiffSpanStyle, into buf: inout [UInt8]) {
        switch value {
        
        
        case .context:
            writeInt(&buf, Int32(1))
        
        
        case .added:
            writeInt(&buf, Int32(2))
        
        
        case .removed:
            writeInt(&buf, Int32(3))
        
        
        case .unchanged:
            writeInt(&buf, Int32(4))
        
        
        case .separator:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffSpanStyle_lift(_ buf: RustBuffer) throws -> DiffSpanStyle {
    return try FfiConverterTypeDiffSpanStyle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffSpanStyle_lower(_ value: DiffSpanStyle) -> RustBuffer {
    return FfiConverterTypeDiffSpanStyle.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum EdgeType: Equatable, Hashable {
    
    case direct
    case indirect
    case missing





}

#if compiler(>=6)
extension EdgeType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEdgeType: FfiConverterRustBuffer {
    typealias SwiftType = EdgeType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EdgeType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .direct
        
        case 2: return .indirect
        
        case 3: return .missing
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EdgeType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .direct:
            writeInt(&buf, Int32(1))
        
        
        case .indirect:
            writeInt(&buf, Int32(2))
        
        
        case .missing:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEdgeType_lift(_ buf: RustBuffer) throws -> EdgeType {
    return try FfiConverterTypeEdgeType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEdgeType_lower(_ value: EdgeType) -> RustBuffer {
    return FfiConverterTypeEdgeType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum HunkType: Equatable, Hashable {
    
    case added
    case removed
    case modified
    case renamed





}

#if compiler(>=6)
extension HunkType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHunkType: FfiConverterRustBuffer {
    typealias SwiftType = HunkType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HunkType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .added
        
        case 2: return .removed
        
        case 3: return .modified
        
        case 4: return .renamed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HunkType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .added:
            writeInt(&buf, Int32(1))
        
        
        case .removed:
            writeInt(&buf, Int32(2))
        
        
        case .modified:
            writeInt(&buf, Int32(3))
        
        
        case .renamed:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHunkType_lift(_ buf: RustBuffer) throws -> HunkType {
    return try FfiConverterTypeHunkType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHunkType_lower(_ value: HunkType) -> RustBuffer {
    return FfiConverterTypeHunkType.lower(value)
}



public enum JayJayError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case RepoNotFound(path: String
    )
    case RevNotFound(rev: String
    )
    case Internal(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension JayJayError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJayJayError: FfiConverterRustBuffer {
    typealias SwiftType = JayJayError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JayJayError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .RepoNotFound(
            path: try FfiConverterString.read(from: &buf)
            )
        case 2: return .RevNotFound(
            rev: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: JayJayError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .RepoNotFound(path):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(path, into: &buf)
            
        
        case let .RevNotFound(rev):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(rev, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayError_lift(_ buf: RustBuffer) throws -> JayJayError {
    return try FfiConverterTypeJayJayError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJayJayError_lower(_ value: JayJayError) -> RustBuffer {
    return FfiConverterTypeJayJayError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SyntaxToken: Equatable, Hashable {
    
    case plain
    case keyword
    case stringLit
    case comment
    case number
    case type
    case function
    case variable
    case `operator`
    case punctuation
    case attribute





}

#if compiler(>=6)
extension SyntaxToken: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyntaxToken: FfiConverterRustBuffer {
    typealias SwiftType = SyntaxToken

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyntaxToken {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .plain
        
        case 2: return .keyword
        
        case 3: return .stringLit
        
        case 4: return .comment
        
        case 5: return .number
        
        case 6: return .type
        
        case 7: return .function
        
        case 8: return .variable
        
        case 9: return .`operator`
        
        case 10: return .punctuation
        
        case 11: return .attribute
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SyntaxToken, into buf: inout [UInt8]) {
        switch value {
        
        
        case .plain:
            writeInt(&buf, Int32(1))
        
        
        case .keyword:
            writeInt(&buf, Int32(2))
        
        
        case .stringLit:
            writeInt(&buf, Int32(3))
        
        
        case .comment:
            writeInt(&buf, Int32(4))
        
        
        case .number:
            writeInt(&buf, Int32(5))
        
        
        case .type:
            writeInt(&buf, Int32(6))
        
        
        case .function:
            writeInt(&buf, Int32(7))
        
        
        case .variable:
            writeInt(&buf, Int32(8))
        
        
        case .`operator`:
            writeInt(&buf, Int32(9))
        
        
        case .punctuation:
            writeInt(&buf, Int32(10))
        
        
        case .attribute:
            writeInt(&buf, Int32(11))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyntaxToken_lift(_ buf: RustBuffer) throws -> SyntaxToken {
    return try FfiConverterTypeSyntaxToken.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyntaxToken_lower(_ value: SyntaxToken) -> RustBuffer {
    return FfiConverterTypeSyntaxToken.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBookmarkInfo: FfiConverterRustBuffer {
    typealias SwiftType = [BookmarkInfo]

    public static func write(_ value: [BookmarkInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBookmarkInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BookmarkInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [BookmarkInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBookmarkInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChangeInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ChangeInfo]

    public static func write(_ value: [ChangeInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChangeInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChangeInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChangeInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChangeInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDiffHunk: FfiConverterRustBuffer {
    typealias SwiftType = [DiffHunk]

    public static func write(_ value: [DiffHunk], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDiffHunk.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DiffHunk] {
        let len: Int32 = try readInt(&buf)
        var seq = [DiffHunk]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDiffHunk.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGraphEdge: FfiConverterRustBuffer {
    typealias SwiftType = [GraphEdge]

    public static func write(_ value: [GraphEdge], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGraphEdge.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GraphEdge] {
        let len: Int32 = try readInt(&buf)
        var seq = [GraphEdge]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGraphEdge.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGraphEntry: FfiConverterRustBuffer {
    typealias SwiftType = [GraphEntry]

    public static func write(_ value: [GraphEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGraphEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GraphEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [GraphEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGraphEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNativeDiffLine: FfiConverterRustBuffer {
    typealias SwiftType = [NativeDiffLine]

    public static func write(_ value: [NativeDiffLine], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNativeDiffLine.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NativeDiffLine] {
        let len: Int32 = try readInt(&buf)
        var seq = [NativeDiffLine]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNativeDiffLine.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNativeDiffSpan: FfiConverterRustBuffer {
    typealias SwiftType = [NativeDiffSpan]

    public static func write(_ value: [NativeDiffSpan], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNativeDiffSpan.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NativeDiffSpan] {
        let len: Int32 = try readInt(&buf)
        var seq = [NativeDiffSpan]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNativeDiffSpan.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeOpLogEntry: FfiConverterRustBuffer {
    typealias SwiftType = [OpLogEntry]

    public static func write(_ value: [OpLogEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeOpLogEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [OpLogEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [OpLogEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeOpLogEntry.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_jayjay_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_abandon() != 13204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_commit_with_submodules() != 30371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_compute_native_diff() != 45440) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_create_bookmark() != 35749) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_delete_bookmark() != 1256) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_delete_files() != 44520) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_describe() != 32905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_diff_summary() != 15222) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_dirty_submodules() != 32967) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_generate_commit_message() != 25182) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_git_fetch() != 44079) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_git_push() != 25924) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_ignore_and_untrack() != 15619) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_jj_commit() != 55764) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_jj_config() != 12861) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_jj_config_path() != 37938) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_list_bookmarks() != 63540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_log() != 41168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_log_graph() != 59717) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_move_bookmark() != 46851) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_new_change() != 15291) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_op_log() != 126) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_op_restore() != 48611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_path() != 44247) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_rebase() != 18128) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_refresh_working_copy() != 2506) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_restore_files() != 62677) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_show() != 24425) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_show_file() != 58452) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_show_summary() != 41214) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_split() != 65138) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_method_jayjayrepo_squash() != 1788) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jayjay_uniffi_checksum_constructor_jayjayrepo_open() != 60052) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureJayjayUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all