use jayjay_core::{DiffProjectionMode, DiffRenderKind, Repo};
use jj_test::FormatFixture;

fn hunk(repo: &Repo, path: &str) -> jayjay_core::DiffHunk {
    repo.show_file("@", path)
        .unwrap_or_else(|err| panic!("show projected {path}: {err}"))
}

fn fixture_repo() -> (FormatFixture, Repo) {
    let fixture = FormatFixture::build();
    let repo = Repo::open(&fixture.path).expect("open repo");
    repo.refresh_working_copy().expect("snapshot");
    (fixture, repo)
}

#[test]
fn summary_marks_text_backed_rich_formats_as_raw_by_default() {
    let (_fixture, repo) = fixture_repo();

    let detail = repo.show_summary("@").expect("show summary");
    for (path, plugin_id) in [
        (FormatFixture::NOTEBOOK, "ipynb"),
        (FormatFixture::CSV, "delimited"),
        (FormatFixture::SARIF, "sarif"),
    ] {
        let hunk = detail
            .diff
            .iter()
            .find(|hunk| hunk.path == path)
            .unwrap_or_else(|| panic!("summary contains {path}"));
        let projection = hunk.projection.as_ref().expect("projection metadata");
        assert_eq!(projection.plugin_id, plugin_id);
        assert_eq!(projection.mode, DiffProjectionMode::Raw);
        assert!(hunk.old.content.is_none());
        assert!(hunk.new.content.is_none());
    }
}

#[test]
fn ipynb_projection_normalizes_cells_and_raw_mode_keeps_source_json() {
    let (_fixture, repo) = fixture_repo();

    let projected = hunk(&repo, FormatFixture::NOTEBOOK);
    let projection = projected.projection.as_ref().expect("projection metadata");
    assert_eq!(projection.plugin_id, "ipynb");
    assert_eq!(projection.mode, DiffProjectionMode::Processed);
    assert_eq!(projection.render_kind, DiffRenderKind::Markdown);
    assert_eq!(projection.virtual_path, "analysis.ipynb.md");
    let content = projected.new.content.as_deref().expect("projected content");
    assert!(content.contains("# Sales Analysis"));
    assert!(
        content.contains(
            "```python\nimport pandas as pd\ndf = pd.read_csv('data.csv')\ndf.head()\n```"
        )
    );
    assert!(content.contains("Generated by an external reporting tool."));
    assert!(!content.contains("<!-- markdown cell -->"));
    assert!(!content.contains("<!-- code cell -->"));
    assert!(!content.contains("<!-- raw cell -->"));
    assert!(!content.contains("execution_count"));
    assert!(!content.contains("volatile table"));

    let raw = repo
        .show_file_raw("@", FormatFixture::NOTEBOOK)
        .expect("show raw notebook");
    assert_eq!(
        raw.projection.as_ref().map(|p| p.mode),
        Some(DiffProjectionMode::Raw)
    );
    assert!(
        raw.new
            .content
            .as_deref()
            .is_some_and(|content| content.contains("execution_count"))
    );
    assert_ne!(projected.review_identity, raw.review_identity);
}

#[test]
fn plist_projection_reads_binary_plist_as_sorted_xml() {
    let (_fixture, repo) = fixture_repo();

    let projected = hunk(&repo, FormatFixture::PLIST);
    let projection = projected.projection.as_ref().expect("projection metadata");
    assert_eq!(projection.plugin_id, "plist");
    assert_eq!(projection.virtual_path, "Info.plist.xml");
    let content = projected.new.content.as_deref().expect("projected content");
    assert!(content.find("<key>a</key>").unwrap() < content.find("<key>z</key>").unwrap());
    assert!(content.contains("<integer>1</integer>"));
    assert!(content.contains("<key>features</key>"));
}

#[test]
fn summary_projects_only_binary_plists() {
    let (_fixture, repo) = fixture_repo();

    let detail = repo.show_summary("@").expect("show summary");
    let binary = detail
        .diff
        .iter()
        .find(|hunk| hunk.path == FormatFixture::PLIST)
        .expect("binary plist hunk");
    assert_eq!(
        binary.projection.as_ref().expect("projected").plugin_id,
        "plist"
    );
    let plain = detail
        .diff
        .iter()
        .find(|hunk| hunk.path == FormatFixture::XML_PLIST)
        .expect("plain plist hunk");
    assert!(plain.projection.is_none());
}

#[test]
fn plain_xml_plist_stays_a_source_diff() {
    let (_fixture, repo) = fixture_repo();

    let plain = hunk(&repo, FormatFixture::XML_PLIST);
    assert!(plain.projection.is_none());
    assert!(
        plain
            .new
            .content
            .as_deref()
            .is_some_and(|content| content.contains("<key>Plain</key>"))
    );
}

#[test]
fn csv_projection_renders_markdown_table() {
    let (_fixture, repo) = fixture_repo();

    let projected = hunk(&repo, FormatFixture::CSV);
    let projection = projected.projection.as_ref().expect("projection metadata");
    assert_eq!(projection.plugin_id, "delimited");
    assert_eq!(projection.render_kind, DiffRenderKind::Table);
    assert_eq!(projection.virtual_path, "data.csv.md");
    assert_eq!(
        projected.new.content.as_deref(),
        Some(
            "| city | quarter | revenue | notes |\n| --- | --- | --- | --- |\n| San Francisco | 2024-Q1 | 1234.50 | quoted, comma |\n| New York | 2024-Q2 |  | line one line two |\n| Remote | 2024-Q3 | 0 | contains \\| pipe and \\\\ slash |\n"
        )
    );
}

#[test]
fn sarif_projection_renders_markdown_report() {
    let (_fixture, repo) = fixture_repo();

    let projected = hunk(&repo, FormatFixture::SARIF);
    let projection = projected.projection.as_ref().expect("projection metadata");
    assert_eq!(projection.plugin_id, "sarif");
    assert_eq!(projection.render_kind, DiffRenderKind::Markdown);
    assert_eq!(projection.virtual_path, "results.sarif.md");
    let content = projected.new.content.as_deref().expect("projected content");
    assert!(content.contains("# SARIF Report"));
    assert!(content.contains("## Run 1: JayJay Security Scan"));
    assert!(content.contains("### JJ001: Shell command injection"));
    assert!(content.contains("- Level: `error`"));
    assert!(content.contains("- Location: `Sources/RepositoryActions.swift:88:17`"));
    assert!(content.contains("- Message: Quote or avoid shell interpolation for branch names."));
    assert!(!content.contains("\"runs\""));

    let raw = repo
        .show_file_raw("@", FormatFixture::SARIF)
        .expect("show raw SARIF");
    assert_eq!(
        raw.projection.as_ref().map(|p| p.mode),
        Some(DiffProjectionMode::Raw)
    );
    assert!(
        raw.new
            .content
            .as_deref()
            .is_some_and(|content| content.contains("\"runs\""))
    );
}

#[test]
fn markdown_source_diff_is_not_projected() {
    let (_fixture, repo) = fixture_repo();

    let markdown = hunk(&repo, FormatFixture::MARKDOWN);
    assert!(markdown.projection.is_none());
    assert!(
        markdown
            .new
            .content
            .as_deref()
            .is_some_and(|content| content.contains("# Notes"))
    );
}
