use gpui::actions;

actions!(
    jayjay,
    [
        OpenSettings,
        OpenAbout,
        CloseWindow,
        Dismiss,
        Refresh,
        OpenRepository,
        OpenCommandPalette,
        OpenFind,
        CopyDiffSelection,
        OpenUserGuide,
        OpenJujutsuDocumentation,
        ReportIssue,
        OpenBookmarkManager,
        OpenOperationLog,
        OpenRepoInEditor,
        OpenRepoInTerminal,
        ShowRepoInFileManager,
        OpenRemoteRepository,
        GitFetchOrigin,
        GitPushDefault,
        ForgetStaleBookmarks,
        ToggleSideBySideDiff,
        ToggleIgnoreWhitespace,
        ToggleHideGitLfsFiles,
        ToggleTreeFileList,
        ZoomIn,
        ZoomOut,
        ResetZoom,
        Quit
    ]
);
