[package]
name = "jayjay-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
jj-lib = { workspace = true }
jj-diff = { path = "../jj-diff" }
thiserror = { workspace = true }
pollster = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
