[package]
name = "jayjay-core"
version = "0.1.0"
description = "Core repository operations for JayJay"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
jj-lib = { workspace = true }
gix = { workspace = true }
gix-url = { workspace = true }
percent-encoding = { workspace = true }
jj-diff = { version = "0.1.0", path = "../jj-diff" }
jayjay-primitives = { version = "0.1.0", path = "../jayjay-primitives" }
jayjay-review = { version = "0.1.0", path = "../jayjay-review" }
jayjay-network = { version = "0.1.0", path = "../jayjay-network" }
nucleo-matcher = { workspace = true }
pollster = { workspace = true }
stacker = { workspace = true }
chrono = { workspace = true }
libc = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
directories = { workspace = true }
toml = { workspace = true }
plist = { workspace = true }
csv = { workspace = true }
dunce = { workspace = true }

[dev-dependencies]
jj-test = { path = "../jj-test" }
tempfile = { workspace = true }
