use jayjay_core::DiffThemeColors;

#[uniffi::remote(Record)]
pub struct DiffThemeColors {
    pub added_bg: u32,
    pub removed_bg: u32,
    pub context_bg: u32,
    pub separator_bg: u32,
    pub conflict_header_bg: u32,
    pub conflict_section_bg: u32,
    pub conflict_content_bg: u32,
    pub conflict_header_fg: u32,
    pub conflict_section_fg: u32,
    pub conflict_stripe: u32,
    pub conflict_stripe_alpha: f64,
    pub added_word_bg: u32,
    pub removed_word_bg: u32,
    pub gutter_bg: u32,
    pub gutter_fg: u32,
    pub gutter_added_fg: u32,
    pub gutter_removed_fg: u32,
    pub text_context: u32,
    pub text_added: u32,
    pub text_removed: u32,
    pub text_dim: u32,
    pub tok_keyword: u32,
    pub tok_string: u32,
    pub tok_comment: u32,
    pub tok_number: u32,
    pub tok_type: u32,
    pub group_stripe: u32,
    pub group_stripe_alpha: f64,
    pub find_match_bg: u32,
    pub find_match_fg: u32,
}
